http://localhost:3000/atividades

###

GET http://localhost:3000/atividades/1

###

POST http://localhost:3000/atividades HTTP/1.1
content-type: application/json

{
    "descricao": "Teste",
    "prioridade": 3,
    "status": "Finalizado"
}

###